//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoBattles.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoogleDriveAuth {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleDriveAuth() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoBattles.App.Resources.GoogleDriveAuth", typeof(GoogleDriveAuth).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDKQV4DD9dRQ2Y1\nVIpt8EPUvOyfvYcB1olGAA1RaEX7oiHkpzdlLrB/B/vqZ74z2FY1AKpy63zsgHhh\nGIJG6uyxPylGWbhemIQrvASDCvMnkFDmf519hG5YzmUiomJ+qg2VobhXGkoFKptn\nmTJzyfJoIzZXs/LkMD/FnJvHZ5Xxv6bGvROk3y68TUnkXLwHAfCv9hGJR2HXyvog\nr5k2O7rWyj05tKM1SQ0XdT/Os3jhyaXEIEdLQwCSa0AGITZW1trg2U0zqyWp2n0j\nQEXUTtxEEcTWSo9UFG8q8O3AtqKWJUEFo/awOsEEtrTh1/CtBEq4Vo/tiKTaL633\nPpsggeZLAgMBAAECggEBAL9pI5bUPBtNJQKdsrCe7SL9dRcsYAPOTHXyAKilfW3K\noDbsRdG9YQ2nubK6YdhhC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoogleDrivePrivateKey {
            get {
                return ResourceManager.GetString("GoogleDrivePrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 440839730918-bl8qakk064m5sahh1hapj6c3pkap1p44@developer.gserviceaccount.com.
        /// </summary>
        internal static string GoogleDriveServiceAccountEmail {
            get {
                return ResourceManager.GetString("GoogleDriveServiceAccountEmail", resourceCulture);
            }
        }
    }
}
